-- Drop the database if it exists
DROP ALL OBJECTS;

-- Create the CART table
CREATE TABLE IF NOT EXISTS CART
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT         NOT NULL,
    NAME        VARCHAR(50) NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID) ON DELETE CASCADE -- Added ON DELETE CASCADE
);


-- Create the CATEGORY table
CREATE TABLE IF NOT EXISTS CATEGORY
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(50) NOT NULL,
    DESCRIPTION CLOB
);

-- Create the CUSTOMER table
CREATE TABLE IF NOT EXISTS CUSTOMER
(
    ID                INT AUTO_INCREMENT PRIMARY KEY,
    NAME              VARCHAR(100)                        NOT NULL,
    PASSWORD          VARCHAR(20)                         NOT NULL,
    LAST_UPDATED      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    REGISTRATION_DATE DATE      DEFAULT CURRENT_DATE      NOT NULL
);

-- Create the PRODUCT table
CREATE TABLE IF NOT EXISTS PRODUCT
(
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    NAME         VARCHAR(50)                         NOT NULL,
    DESCRIPTION  CLOB                                NOT NULL,
    PRICE        DECIMAL(5, 2)                       NOT NULL,
    STOCK_QTY    INT                                 NOT NULL,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CATEGORY_ID  INT                                 NOT NULL,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID) ON DELETE CASCADE -- Added ON DELETE CASCADE
);

-- Create the CART_ITEM table
CREATE TABLE IF NOT EXISTS CART_ITEM
(
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    CART_ID      INT                                 NOT NULL,
    PRODUCT_ID   INT                                 NOT NULL,
    ITEM_QTY     INT                                 NOT NULL,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (CART_ID) REFERENCES CART (ID) ON DELETE CASCADE,      -- Added ON DELETE CASCADE
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID) ON DELETE CASCADE -- Added ON DELETE CASCADE
);
-- Create indexes
CREATE INDEX IF NOT EXISTS FK_CUSTOMERCART_INDEX_1 ON CART (CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS FK_CARTITEMPRODUCT_INDEX_B ON CART_ITEM (PRODUCT_ID);
CREATE UNIQUE INDEX IF NOT EXISTS UNIQUE_NAME_INDEX_F ON CATEGORY (NAME);
CREATE INDEX IF NOT EXISTS FK_PRODUCTCATEGORY_INDEX_1 ON PRODUCT (CATEGORY_ID);

